
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (P_CATEGORY) REFERENCES CATEGORIES(C_ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_IMAGES FOREIGN KEY (P_IMAGE) REFERENCES IMAGES(I_ID);
ALTER TABLE USER_DETAILS ADD CONSTRAINT FK_USER_DETAILS_USERS FOREIGN KEY (UD_USER_ID) REFERENCES USERS(U_ID);
ALTER TABLE USER_DETAILS ADD CONSTRAINT FK_USER_DETAILS_USER_ACCOUNT_TYPE FOREIGN KEY (UD_AC_TYPE) REFERENCES USER_ACCOUNT_TYPE(UAT_ID);
ALTER TABLE USER_DETAILS ADD CONSTRAINT FK_USER_DETAILS_USER_TYPE FOREIGN KEY (UD_TYPE) REFERENCES USER_TYPE(UT_ID);
ALTER TABLE ORDERS_REGISTER ADD CONSTRAINT FK_ORDERS_REGISTER_USERS FOREIGN KEY (O_USER_ID) REFERENCES USERS(U_ID);
ALTER TABLE ORDERS_DETAILS ADD CONSTRAINT FK_ORDERS_DETAILS_ORDERS_REGISTER FOREIGN KEY (OD_ORDER_REGISTER_ID) REFERENCES ORDERS_REGISTER(O_ID);
ALTER TABLE ORDERS_DETAILS ADD CONSTRAINT FK_ORDERS_DETAILS_PRODUCTS FOREIGN KEY (OD_PRODUCT_ID) REFERENCES PRODUCTS(P_ID);
ALTER TABLE TEMP_ORDERS_REGISTER ADD CONSTRAINT FK_TEMP_ORDERS_REGISTER_USERS FOREIGN KEY (TO_USER_ID) REFERENCES USERS(U_ID);
ALTER TABLE TEMP_ORDERS_DETAILS ADD CONSTRAINT FK_TEMP_ORDERS_DETAILS_TEMP_ORDERS_REGISTER FOREIGN KEY (TOD_ORDER_REGISTER_ID) REFERENCES TEMP_ORDERS_REGISTER(TO_ID);
ALTER TABLE TEMP_ORDERS_DETAILS ADD CONSTRAINT FK_TEMP_ORDERS_DETAILS_PRODUCTS FOREIGN KEY (TOD_PRODUCT_ID) REFERENCES PRODUCTS(P_ID);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_USERS FOREIGN KEY (CM_USER_ID) REFERENCES USERS(U_ID);
ALTER TABLE COMMENTS_DETAILS ADD CONSTRAINT FK_COMMENTS_DETAILS_COMMENTS FOREIGN KEY (CMD_COMMENT_ID) REFERENCES COMMENTS(CM_ID);
ALTER TABLE COMMENTS_DETAILS ADD CONSTRAINT FK_COMMENTS_DETAILS_PRODUCTS FOREIGN KEY (CMD_PRODUCT_ID) REFERENCES PRODUCTS(P_ID);
ALTER TABLE RATING ADD CONSTRAINT FK_RATING_PRODUCTS FOREIGN KEY (R_PRODUCT_ID) REFERENCES PRODUCTS(P_ID);