/*products*/
CREATE TABLE PRODUCTS (
    P_ID INT PRIMARY KEY IDENTITY(1,1),
    P_NAME NVARCHAR(50) NOT NULL,
    P_DESCRIPTION NVARCHAR(50) NOT NULL,
    P_PRICE DECIMAL(20, 2) NOT NULL,
    P_CATEGORY INT NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*category*/

CREATE TABLE CATEGORIES (
    C_ID INT PRIMARY KEY IDENTITY(1,1),
    C_NAME NVARCHAR(50) NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*images*/

CREATE TABLE IMAGES (
    I_ID INT PRIMARY KEY IDENTITY(1,1),
    I_NAME NVARCHAR(50) NOT NULL,
    I_PATH NVARCHAR(50) NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user login*/
CREATE TABLE USERS (
    U_ID INT PRIMARY KEY IDENTITY(1,1),
    U_EMAIL NVARCHAR(100) NOT NULL,
    U_PASS NVARCHAR(50) NOT NULL,
    U_IMAGE IMAGE NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user detials*/

CREATE TABLE USER_DETAILS (
    UD_ID INT PRIMARY KEY IDENTITY(1,1),
    UD_FNAME NVARCHAR(50) NOT NULL,
    UD_LNAME NVARCHAR(50) NOT NULL,
    UD_AC_TYPE INT NOT NULL,
    UD_TYPE INT NOT NULL,
    UD_USER_ID INT NOT NULL,
    UD_ADDRESS NVARCHAR(200) NULL,
    UD_PHONE NVARCHAR(50) NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user account type*/

CREATE TABLE USER_ACCOUNT_TYPE (
    UAT_ID INT PRIMARY KEY IDENTITY(1,1),
    UAT_NAME NVARCHAR(50) NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user type*/

CREATE TABLE USER_TYPE (
    UT_ID INT PRIMARY KEY IDENTITY(1,1),
    UT_NAME NVARCHAR(50) NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user orders register*/

CREATE TABLE ORDERS_REGISTER (
    O_ID INT PRIMARY KEY IDENTITY(1,1),
    O_USER_ID INT NOT NULL,
    O_EMAIL NVARCHAR(100) NOT NULL,
    O_ADDRESS NVARCHAR(200) NOT NULL,
    O_PHONE NVARCHAR(50) NOT NULL,
    O_COUNT INT NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user orders details*/

CREATE TABLE ORDERS_DETAILS (
    OD_ID INT PRIMARY KEY IDENTITY(1,1),
    OD_ORDER_REGISTER_ID INT NOT NULL,
    OD_TRACKING_ID NVARCHAR(50) NOT NULL,   
    OD_PRODUCT_ID INT NOT NULL,
    OD_QUANTITY INT NOT NULL,
    OD_PRICE DECIMAL(20, 2) NOT NULL,
    OD_TOTAL_PRICE DECIMAL(20, 2) NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user temp order register*/

CREATE TABLE TEMP_ORDERS_REGISTER (
    TO_ID INT PRIMARY KEY IDENTITY(1,1),
    TO_USER_ID NVARCHAR(50) NOT NULL,
    TO_NAME NVARCHAR(50) NOT NULL,
    TO_EMAIL NVARCHAR(100) NOT NULL,
    TO_ADDRESS NVARCHAR(200) NOT NULL,
    TO_PHONE NVARCHAR(50) NOT NULL,
    TO_COUNT INT NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user temp order details*/

CREATE TABLE TEMP_ORDERS_DETAILS (
    TOD_ID INT PRIMARY KEY IDENTITY(1,1),
    TOD_ORDER_REGISTER_ID INT NOT NULL,
    TOD_TRACKING_ID NVARCHAR(50) NOT NULL,   
    TOD_PRODUCT_ID INT NOT NULL,
    TOD_QUANTITY INT NOT NULL,
    TOD_PRICE DECIMAL(20, 2) NOT NULL,
    TOD_TOTAL_PRICE DECIMAL(20, 2) NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*user contact*/

CREATE TABLE CONTACT (
    C_ID INT PRIMARY KEY IDENTITY(1,1),
    C_NAME NVARCHAR(50) NOT NULL,
    C_EMAIL NVARCHAR(100) NOT NULL,
    C_PHONE NVARCHAR(50) NOT NULL,
    C_ADDRESS NVARCHAR(200) NOT NULL,
    C_MESSAGE NVARCHAR(500) NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*comments*/

CREATE TABLE COMMENTS (
    CM_ID INT PRIMARY KEY IDENTITY(1,1),
    CM_USER_ID INT NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*comments details*/

CREATE TABLE COMMENTS_DETAILS (
    CMD_ID INT PRIMARY KEY IDENTITY(1,1),
    CMD_COMMENT_ID INT NOT NULL,
    CMD_PRODUCT_ID INT NOT NULL,
    CMD_MESSAGE NVARCHAR(500) NULL,
    CMD_RATE INT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*rating*/

CREATE TABLE RATING (
    R_ID INT PRIMARY KEY IDENTITY(1,1),
    R_PRODUCT_ID INT NOT NULL,
    R_RATE INT NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*admin*/

CREATE TABLE ADMIN (
    A_ID INT PRIMARY KEY IDENTITY(1,1),
    A_NAME NVARCHAR(50) NOT NULL,
    A_EMAIL NVARCHAR(100) NOT NULL,
    A_PASS NVARCHAR(50) NOT NULL,
    A_IMAGE IMAGE NOT NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
);

/*forign keys*/

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (P_CATEGORY) REFERENCES CATEGORIES(C_ID);

/*drop all tables*/

DROP TABLE PRODUCTS;
DROP TABLE CATEGORIES;
DROP TABLE USERS;
DROP TABLE USER_DETAILS;
DROP TABLE IMAGES;
DROP TABLE USER_ACCOUNT_TYPE;
DROP TABLE USER_TYPE;
DROP TABLE ORDERS_REGISTER;
DROP TABLE ORDERS_DETAILS;
DROP TABLE TEMP_ORDERS_REGISTER;
DROP TABLE TEMP_ORDERS_DETAILS;
DROP TABLE CONTACT;
DROP TABLE COMMENTS;
DROP TABLE COMMENTS_DETAILS;
DROP TABLE RATING;
DROP TABLE ADMIN;


